# Read in data to work with for Limma analysis (so analysis does not need to be rerun)
L2_3_IT_Limma_stat_sig <- read.csv(file = "~/GitHub/snRNA-seq-pipeline/DEG_data/stat_sig/L2_3_IT_Limma_DEG_only_stat_sig.csv")
L6_Limma_stat_sig <- read.csv(file = "~/GitHub/snRNA-seq-pipeline/DEG_data/stat_sig/L6_Limma_DEG_only_stat_sig.csv")
Sst_Limma_stat_sig <- read.csv(file = "~/GitHub/snRNA-seq-pipeline/DEG_data/stat_sig/Sst_Limma_DEG_only_stat_sig.csv")
L5_Limma_stat_sig <- read.csv(file = "~/GitHub/snRNA-seq-pipeline/DEG_data/stat_sig/L5_Limma_DEG_only_stat_sig.csv")
L4_Limma_stat_sig <- read.csv(file = "~/GitHub/snRNA-seq-pipeline/DEG_data/stat_sig/L4_Limma_DEG_only_stat_sig.csv")
Pvalb_Limma_stat_sig <- read.csv(file = "~/GitHub/snRNA-seq-pipeline/DEG_data/stat_sig/Pvalb_Limma_DEG_only_stat_sig.csv")
Sncg_Limma_stat_sig <- read.csv(file = "~/GitHub/snRNA-seq-pipeline/DEG_data/stat_sig/Sncg_Limma_DEG_only_stat_sig.csv")
Non_neuronal_Limma_stat_sig <- read.csv(file = "~/GitHub/snRNA-seq-pipeline/DEG_data/stat_sig/Non_neuronal_Limma_DEG_only_stat_sig.csv")
Oligo_Limma_stat_sig <- read.csv(file = "~/GitHub/snRNA-seq-pipeline/DEG_data/stat_sig/Oligo_Limma_DEG_only_stat_sig.csv")
Vip_Limma_stat_sig <- read.csv(file = "~/GitHub/snRNA-seq-pipeline/DEG_data/stat_sig/Vip_Limma_DEG_only_stat_sig.csv")
Lamp5_Limma_stat_sig <- read.csv(file = "~/GitHub/snRNA-seq-pipeline/DEG_data/stat_sig/Lamp5_Limma_DEG_only_stat_sig.csv")
Astro_Limma_stat_sig <- read.csv(file = "~/GitHub/snRNA-seq-pipeline/DEG_data/stat_sig/Astro_Limma_DEG_only_stat_sig.csv")
Peri_Limma_stat_sig <- read.csv(file = "~/GitHub/snRNA-seq-pipeline/DEG_data/stat_sig/Peri_Limma_DEG_only_stat_sig.csv")
Endo_Limma_stat_sig <- read.csv(file = "~/GitHub/snRNA-seq-pipeline/DEG_data/stat_sig/Endo_Limma_DEG_only_stat_sig.csv")
